### PR TITLE
Fix XSS vulnerability

### PR DESCRIPTION
**Pull request by jrief**
Up to version 3.8.0, djangocms-text-ckeditor shipped with CKEditor version 4.7.3.
According to the official release notes, a [XSS vulnerability has been fixed in version 4.11.0](https://ckeditor.com/cke4/release/CKEditor-4.11.0).

**Therefore an upgrade of CKEditor is highly recommended.**

This pull request upgrades CKEditor to the latest current release, namely 4.13.1. 
In a first manual test, everything seems to work as usual.

### CODE REVIEW

**Comment by jrief** [comment]
Since tox installs formtools for Python-3 only, and since Python-2.7 is end-of-life since January, 1st. I removed that from the unit tests together with Python-3.4.

**Comment by jrief** [comment]
Just found out that text-enabled CMS plugins do not work. It seems as if the internal API of CKEDitor changed and version 4.7.3 is not compatible with 4.13.1 anymore. It fails with an error: function `setModel` not found.

**Comment by FinalAngel** [comment]
@jrief I'll have an additional look after https://github.com/divio/djangocms-text-ckeditor/pull/511 gets merged. I'd still like to keep the old support going for this release and then remove it on the next (alongside all the other addons and CMS itself as well)

**Comment by yakky** [comment]
@jrief I agree with @FinalAngel if you could readd the python version drops I think we should merge and release this ASAP together with #510

**Comment by yakky** [comment]
@jrief how about restoring python 2.7 here and merge this together with #510 as 3.9.1?

**Comment by jrief** [comment]
@yakky the biggest problem with this pulls request is, that CMS plugins are not working.

I'm strictly against supporting Python-2 and Django<2.2. These versions are deprecated and not maintained anymore, so we should *not support* for them in newer versions. These compatibility layers always add a lot of cruft, which makes the software much harder the maintain.

Removing Python-2 support from all of my projects was a huge relief for me.

**Comment by yakky** [comment]
@jrief sorry, I missed the message with the updates. We need one of the frontend folks to have a look at it

WRT removing Python 2 & C, I am all for it, I suggested to restore them temporarely to be able to release now as patch version to fix the ckeditor issue. As this seems no longer possible, this is no longer relevant

**Comment by jrief** [comment]
Closing because #534 now really fixes this bug.

**Pull request closed without merging**
