### PR TITLE
Fixed data corruption issue when deleting child plugins

### LINKED ISSUE #212: Data corruption on child plugin delete
I have a model with a PlaceholderField that allows TextPlugin and TextPlugins in turn can have many nested plugins. I'm finding that if I create a new TextPlugin, then add a LinkPlugin (aka select it from the plugins list and hit ok so it's entered into the WYSIWYG) BUT then delete the plugin before saving I get a 500 error.

The problem is that on save, the [text plugin checks](https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/models.py#L46-L52) to see if there are any child plugins that need to be deleted (because they are no longer present in the HTML). This in turn calls plugin.delete() which is actually a [django-treebeard](https://github.com/tabo/django-treebeard/blob/master/treebeard/mp_tree.py#L51-L88) method that updates the `numchild` attribute of the parent of the plugins it is deleting (the parent in this case is the text plugin). 

However, the text plugin then immediately overrides when it [calls save](https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/cms_plugins.py#L112-L114) in the next line, since it has the old numchild attribute. Here are the offending data altering SQL statements in order of execution:

    UPDATE "cms_cmsplugin" SET "path" = \'00N9\', "depth" = 1, "numchild" = 0, "placeholder_id" = 852, "parent_id" = NULL, "position" = 0, "language" = \'en-us\', "plugin_type" = \'TextPlugin\', "creation_date" = \'2015-01-06 21:22:18.739244+00:00\', "changed_date" = \'2015-01-06 22:39:06.979841+00:00\' WHERE "cms_cmsplugin"."id" = 2986

    DELETE FROM "myapp_customlink" WHERE "myapp_customlink"."cmsplugin_ptr_id" IN (2989)
    DELETE FROM "cms_cmsplugin" WHERE "cms_cmsplugin"."id" IN (2989)

    UPDATE "cms_cmsplugin" SET "path" = \'00N9\', "depth" = 1, "numchild" = 1, "placeholder_id" = 852, "parent_id" = NULL, "position" = 0, "language" = \'en-us\', "plugin_type" = \'TextPlugin\', "creation_date" = \'2015-01-06 21:22:18.739244+00:00\', "changed_date" = \'2015-01-06 22:49:25.451139+00:00\' WHERE "cms_cmsplugin"."id" = 2986

    UPDATE "djangocms_text_ckeditor_text" SET "body" = \'<p>asdfas</p>\n\n<p>asdfasdf</p>\n\' WHERE "djangocms_text_ckeditor_text"."cmsplugin_ptr_id" = 2986

The first UPDATE is from django-treebeard setting the numchild to 0, then the child plugin is deleted in the following DELETE statements. djangocms-text-ckeditor is then responsible for the last two UPDATE queries when it saves itself.

Not sure the best way to fix since call `obj.clean_plugins()` can have the side effect of calling save() on obj's CMSPlugin instance before it's had a chance to save itself, leading the values to be out of sync. Need to come up with a generalizable solution that is documented so all plugins that allow children plugins can benefit. Will create a documentation ticket upstream.

### PR DESCRIPTION
**Pull request by jsma**
Fixes #212

### CODE REVIEW

**Comment by yakky** [comment]
LGTM
@ojii @mkoistinen anything I overlooked?

**Comment by jsma** [comment]
Anything else needed to get this merged?

**Comment by yakky** [comment]
@jsma not on your side. Waiting for another set of eyeballs to review this

**Comment by yakky** [comment]
Ok, good for me, merging

**Pull request merged**
