### PR TITLE
Add css properties

### PR DESCRIPTION
**Pull request by rafaelgontijo**
I have created additional settings for exceptions of css properties during parsing.

### CODE REVIEW

**Comment by rafaelgontijo** [comment]
Hello, is there any impediment to this change?

**Comment by rafaelgontijo** [comment]
@czpython You could review this pull request please?

**Comment by vThaian** [comment]
Thanks for your contribution @rafaelgontijo. Could you please resolve conflicts in `html.py`?

**Comment by FinalAngel** [comment]
closing until conflicts are solved

**Pull request closed without merging**
