### PR TITLE
Add plugin module/name settings

### PR DESCRIPTION
**Pull request by suquant**

### CODE REVIEW

**Comment by FinalAngel** [comment]
thank you very much for the PR @suquant 
@yakky is this valid for you? though tests are failing...

**Comment by yakky** [comment]
@suquant nice! could you fix the isort errors?
@FinalAngel wondering if we might want a generic way to do this in the CMS

**Comment by FinalAngel** [comment]
@yakky how would we do this generically? The plugin should probably set this in general. Less logic @cms :D

**Comment by yakky** [comment]
@FinalAngel a setting in the CMS that allows to override module and name for plugin classes. This is not the place to discuss this, though. Will post on ML

**Comment by yakky** [comment]
@FinalAngel merging this
@suquant thanks!

**Pull request merged**
