### PR TITLE
Expand ckeditor if alone in a model popup for Django >= 1.7

### LINKED ISSUE #261: inner iFrame not expanding to full container size
See an example here:

screen shot 2015-07-31 at 4 11 51 pm

These seem to be the relevant installed packages:

    $ pip freeze
    cmsplugin-filer==0.10.2
    Django==1.7.9
    django-cms==3.0.14
    django-filer==0.9.12
    django-mptt==0.6.1
    djangocms-admin-style==0.2.7
    djangocms-text-ckeditor==2.5.3

This happens in the latest Chrome, Firefox, and Safari. I've run `collectstatic` and checked all file permissions; I don't see any 404's in the logs or the browser dev tools.

### PR DESCRIPTION
**Pull request by jgoettsch**
Fixes #261: "Inner Frame not expanding to full container size."

### CODE REVIEW

**Comment by yakky** [comment]
@jgoettsch nice!

**Comment by vxsx** [comment]
would be great if we could merge it

**Comment by yakky** [comment]
@vxsx @lory87 merged!

**Comment by vxsx** [comment]
thanks a lot!

**Pull request merged**
